### ISSUE TITLE
Could you please create and publish a newer version?

### ISSUE THREAD

**Issue by Jimexist** [christophertrudel/node_acl_knex#13]
Some fixes are quite useful after the prvious release.
Thanks

**Comment by christophertrudel** [comment]
Very busy these days. As soon as I get some downtime I will be more than happy too. In the meantime if you are up to it you can submit a pull request for the update.

**Comment by lmammino** [comment]
Is this still open?

**Comment by christophertrudel** [comment]
https://github.com/christophertrudel/node_acl_knex/issues/17
