### ISSUE TITLE
Could you please release last changes and publish them on npm

### ISSUE THREAD

**Issue by ttarnowski** [christophertrudel/node_acl_knex#17]
Issues like https://github.com/christophertrudel/node_acl_knex/issues/8 are already resolved only thing we need is to release these changes and publish them on npm.

**Comment by christophertrudel** [comment]
Been pretty busy lately. Will make some time for it some time this week.

**Comment by lmammino** [comment]
What's the status of this?

Also, given that you use travis, you can [fairly easily](https://docs.travis-ci.com/user/deployment/npm/) delegate to travis the role of deploying to NPM every time there is a new tag/release.

**Comment by christophertrudel** [comment]
Sorry for the delay gentleman.  @lmammino will hook this into Travis some day but for now I just manually published to NPM.
https://www.npmjs.com/package/acl-knex

**Comment by lmammino** [comment]
Thanks a million @christophertrudel
