### ISSUE TITLE
missing "acl_roles" relation with node-acl 0.4.7

### ISSUE THREAD

**Issue by jfgirard** [christophertrudel/node_acl_knex#8]
I'm testing your module with a Postgresql backend and have the following error:
`error: relation "acl_roles" does not exist`  when I do `acl.addUserRoles`.  That table is not being created using `backend.setup`.

The error vanish if I use node-acl 0.4.3 instead of 0.4.7.

I looks like one more table is necessary.

**Comment by carera** [comment]
+1

**Comment by jeremy-meier** [comment]
+1

**Comment by dradux** [comment]
+1

**Comment by Snugug** [comment]
+1

**Comment by ttarnowski** [comment]
+1

**Comment by christophertrudel** [comment]
https://github.com/christophertrudel/node_acl_knex/issues/17
